version: "3"

services:
  redis:
    image: "redis:4.0.11-alpine"
    restart: always

  nginx:
    image: "arnau/nginx-gate"
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/bearer.lua:/bearer.lua
    env_file: ./backend/.env
    ports:
      - "8000:80"
    depends_on:
      - web

  web:
    build:
      context: ./docker/http
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./backend:/code
    command: gunicorn --bind 0.0.0.0:8000 --worker-class aiohttp.GunicornWebWorker --reload --chdir=/code app:server
